// Mocks generated by Mockito 5.0.7 from annotations
// in little_flower_app/test/lib/ki_board_manager_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:little_flower_app/model/ki_board.dart' as _i2;
import 'package:little_flower_app/repo/ki_board_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

class _FakeKiBoard extends _i1.Fake implements _i2.KiBoard {}

/// A class which mocks [KiBoardRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockKiBoardRepository extends _i1.Mock implements _i3.KiBoardRepository {
  MockKiBoardRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void saveKiBoard(String? boardId, _i2.KiBoard? kiBoard) =>
      super.noSuchMethod(Invocation.method(#saveKiBoard, [boardId, kiBoard]),
          returnValueForMissingStub: null);
  @override
  _i4.Future<_i2.KiBoard> getKiBoard(String? boardId) =>
      (super.noSuchMethod(Invocation.method(#getKiBoard, [boardId]),
              returnValue: Future<_i2.KiBoard>.value(_FakeKiBoard()))
          as _i4.Future<_i2.KiBoard>);
}
