name: Little Flower App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'
      - run: echo $ANDROID_KEY_STORE | base64 -di > android/app/key.jks
        env:
          ANDROID_KEY_STORE: ${{ secrets.ANDROID_KEY_STORE }}
      - run: echo $GOOGLE_SERVICE | base64 -di > android/app/google-services.json
        env:
          GOOGLE_SERVICE: ${{ secrets.GOOGLE_SERVICE }}
      - run: flutter pub get
      - run: flutter test
      - run: flutter build appbundle
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
      - name: upload appbundle
        uses: actions/upload-artifact@v2
        with:
          name: app bundle
          path: build/app/outputs/bundle/release/app-release.aab
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - run: echo $ANDROID_PLAY_SECRET | base64 -di > script/key.json
        env:
          ANDROID_KEY_STORE: ${{ secrets.ANDROID_PLAY_SECRET }}
      - name: setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: download bundle
        uses: actions/download-artifact@v2
        with:
          name: app bundle
      - run: |
          pip install google-api-python-client
          pip install oauth2client
          cd script
          python deploy.py com.paulwu.little_flower_app build/app/outputs/bundle/release/app-release.aab internal